me: CI/CD Pipeline



on:

    push:

          branches:

                  - main



          jobs:

              build-and-deploy:

                    runs-on: ubuntu-latest



                        steps:

                                - name: Checkout Code

                                        uses: actions/checkout@v3



                                              - name: Set up JDK 17

                                                      uses: actions/setup-java@v3

                                                              with:

                                                                          java-version: '17'



                                                                                - name: Build with Maven

                                                                                        run: mvn clean package -DskipTests



                                                                                              - name: Build Docker Image

                                                                                                      run: docker build -t myapp .



                                                                                                            - name: Deploy to EC2 via SSH

                                                                                                                    uses: appleboy/ssh-action@v1.0.0

                                                                                                                            with:

                                                                                                                                        host: ${{ secrets.EC2_HOST }}

                                                                                                                                                  username: ${{ secrets.EC2_USER }}

                                                                                                                                                            key: ${{ secrets.EC2_KEY }}

                                                                                                                                                                      script: |

                                                                                                                                                                                    docker stop myapp || true

                                                                                                                                                                                                docker rm myapp || true

                                                                                                                                                                                                            docker rmi myapp || true

                                                                                                                                                                                                                        cd /home/ec2-user/myapp/

                                                                                                                                                                                                                                    git pull origin main

                                                                                                                                                                                                                                                docker build -t myapp .

                                                                                                                                                                                                                                                            docker run -d -p 8080:8080 --name myapp myapp


