name: Build and Deploy Spring Boot App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build Spring Boot App
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t vinod323/gemini-llm .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push vinod323/gemini-llm

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull vinod323/gemini-llm
          docker stop app || true
          docker rm app || true
          docker run -d -p 8080:8080 --name app vinod323/gemini-llm

